### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by AryanKalwani** [AryanKalwani/deveet#2]
This project will really benefit if it has proper documentation.

**Comment by SuNiL-Chau** [comment]
I would like to contribute.

**Comment by AryanKalwani** [comment]
@SuNiL-Chau Sure go ahead!

**Comment by SuNiL-Chau** [comment]
Thank you will start right away.

**Comment by SuNiL-Chau** [comment]
hey checkout documentation & do add Licence.md which is missing MIT licence would work.

**Comment by AryanKalwani** [comment]
Yeah I did that and merged your request. Thanks!
